# Generated by Django 3.1.2 on 2020-10-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20201025_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='year_published',
            field=models.DateField(blank=True, default=1980, null=True, verbose_name='Год публикации'),
        ),
    ]
