# Generated by Django 3.1.2 on 2020-11-10 17:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20201027_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='year_published',
            field=models.PositiveSmallIntegerField(blank=True, help_text='В формате <YYYY>', null=True, validators=[django.core.validators.MinValueValidator(1500), django.core.validators.MaxValueValidator(2020)], verbose_name='Год публикации'),
        ),
    ]
