# Generated by Django 3.1.2 on 2020-11-21 20:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20201110_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='books/', verbose_name='Фото обложки'),
        ),
        migrations.AlterField(
            model_name='book',
            name='year_published',
            field=models.PositiveSmallIntegerField(blank=True, help_text='В формате "YYYY"', null=True, validators=[django.core.validators.MinValueValidator(1500), django.core.validators.MaxValueValidator(2020)], verbose_name='Год публикации'),
        ),
    ]
