# Generated by Django 3.1.2 on 2020-11-21 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20201121_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='foto',
            field=models.ImageField(default='text.txt', upload_to='books/', verbose_name='Фото обложки'),
            preserve_default=False,
        ),
    ]
