# Generated by Django 3.1.2 on 2020-12-18 19:01

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_book_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='foto',
            field=models.ImageField(upload_to=products.models.upload, verbose_name='Фото обложки'),
        ),
    ]
