# Generated by Django 3.1.2 on 2020-10-20 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeRestriction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_restrictions', models.CharField(default='не указаны', help_text='Указываются возрастные ограничения', max_length=10, verbose_name='Возрастные ограничения')),
            ],
            options={
                'verbose_name': 'Возрастные ограничения',
                'verbose_name_plural': 'Возрастные ограничения',
            },
        ),
        migrations.CreateModel(
            name='Binding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('binding_type', models.CharField(max_length=255, verbose_name='Тип переплёта')),
            ],
            options={
                'verbose_name': 'Тип переплёта',
                'verbose_name_plural': 'Тип переплёта',
            },
        ),
        migrations.CreateModel(
            name='BookFormat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_format', models.CharField(default='не указан', max_length=255, verbose_name='Формат')),
            ],
            options={
                'verbose_name': 'Формат',
                'verbose_name_plural': 'Формат',
            },
        ),
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Автор', 'verbose_name_plural': 'Авторы'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.AlterModelOptions(
            name='publisher',
            options={'verbose_name': 'Издательство', 'verbose_name_plural': 'Издательства'},
        ),
        migrations.AlterModelOptions(
            name='series',
            options={'verbose_name': 'Серия', 'verbose_name_plural': 'Серия'},
        ),
    ]
