# Generated by Django 3.1.2 on 2020-11-04 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_auto_20201020_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='series', to='directory.author', verbose_name='Автор'),
        ),
    ]
