# Generated by Django 3.1.2 on 2020-11-22 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_bookincart'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookincart',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6, verbose_name='Price'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookincart',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Quantity'),
        ),
    ]
