# Generated by Django 3.1.2 on 2020-11-22 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20201121_2115'),
        ('orders', '0003_auto_20201122_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookincart',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='books_in_carts', to='products.book'),
            preserve_default=False,
        ),
    ]
