# Generated by Django 3.1.2 on 2020-11-29 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-create_date']},
        ),
    ]
