# Generated by Django 3.1.2 on 2020-12-02 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_order_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='adress',
            field=models.TextField(blank=True, null=True, verbose_name='Адрес доставки'),
        ),
    ]
